apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
    prometheus: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.apacheExporter.enabled }}
    - port: 9117
      targetPort: prometheus
      protocol: TCP
      name: prometheus
{{- end }}
  selector: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 4 }}
