name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Install helm
        uses: azure/setup-helm@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files
        env:
          SKIP: helm-lock
      - run: git diff
        if: failure()
      - name: Checks
        run: c2cciutils-checks

      - run: helm dependency update .
      - run: helm lint .
      - run: helm lint --values=tests/qgis.yaml .
      - run: helm template --namespace=default --values=tests/mapserver.yaml mapserver . > tests/mapserver-actual.yaml
      - run: diff --ignore-trailing-space tests/mapserver-actual.yaml tests/mapserver-expected.yaml
      - run: helm template --namespace=default --values=tests/qgis.yaml qgis . > tests/qgis-actual.yaml
      - run: diff --ignore-trailing-space tests/qgis-actual.yaml tests/qgis-expected.yaml

      - name: Setup k3s/k3d
        run: c2cciutils-k8s-install

      - name: Launch MapServer
        run: kubectl apply -f tests/mapserver-expected.yaml
      - run: c2cciutils-k8s-wait
      - run: c2cciutils-k8s-logs
        if: always()
      - run: kubectl delete -f tests/mapserver-expected.yaml || true

      - name: Create a test-pg database
        run: c2cciutils-k8s-db --script=tests/demo_schema.sql

      - name: Launch QGIS Server
        run: kubectl apply -f tests/qgis-expected.yaml
      - run: c2cciutils-k8s-wait
      - run: c2cciutils-k8s-logs
        if: always()
      - run: kubectl delete -f tests/qgis-expected.yaml || true

      - name: Clean the database
        run: c2cciutils-k8s-db --cleanup
        if: always()

      - name: Publish
        run: c2cciutils-publish
        if: env.HAS_SECRETS == 'HAS_SECRETS'
