---
name: Continuous integration

on:
  push:
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - uses: azure/setup-helm@v1
      - run: helm lint mapserver
      - run: helm template test mapserver

      - run: git config --global user.email ci@camptocamp.com
      - run: git config --global user.name CI
      - run: |
          cd /tmp
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          mv cr /usr/bin
      - run: >
          cr package mapserver
        if: github.event_name == 'push'
      - run: >
          cr upload --owner=camptocamp --git-repo=helm-mapserver --commit=${{ github.sha }} --release-name-template='{{ .Version }}'
        if: github.event_name == 'push'
      - run: >
          cr index --owner=camptocamp --git-repo=helm-mapserver --charts-repo=https://camptocamp.github.io/helm-mapserver
          --push --release-name-template='{{ .Version }}'
        if: github.event_name == 'push'
        #if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, '[release] ')
